### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by cldwalker** [one-more-minute/Reminisce#9]
Hey Mike,
  Could you cut a new release? Since we [released 0.8.0-alpha yesterday](https://groups.google.com/forum/#!topic/light-table-discussion/rkfHTplo4ss) and [Recall isn't electron compatible](https://github.com/joshuafcole/recall/issues/19), I'd love to point users to your plugin without having them git clone.

**Comment by one-more-minute** [comment]
Would be great to do a release, although I'm a bit out of date on the release process. If you want it done sooner rather than later, would it help for me to give you commit access? I could even transfer this to the LT org or something if that's helpful.

**Comment by cldwalker** [comment]
You just need to bump plugin.edn to the next version, 0.3.4, git tag 0.3.4 and push the tag. Happy to do this if you don't have time and give me commit access.From there any committer can make that tag official on https://github.com/LightTable/plugin-metadata/.  Transferring it may be something to consider down the road if enough users come to rely on this

**Comment by cldwalker** [comment]
ping

**Comment by one-more-minute** [comment]
Sorry for the delay, have given you access!

**Comment by cldwalker** [comment]
Thanks for the access. Released!
